name: News Video Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Arabic fonts
        run: |
          sudo apt install -y fonts-dejavu-core
          fc-cache -f -v

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python news_pipeline.py

      - name: Commit last_news.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add last_news.txt

          git diff --cached --quiet || git commit -m "update last news"

          git push
